import { brand } from "@/lib/brand";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

const resources = [
  ["Product resources", ["Evidence-backed website, SEO, social, reviews, goals, and available competitor assessment", "Prioritized Action Plan and recommendation tracking", "Implementation Help drafts, AI Consultant, PDF report, and Presentation Mode", "Full Audit is one-time; Starter and Pro are monthly plans as shown on Pricing"]],
  ["Promotion ideas", ["Record a transparent product walkthrough", "Teach the difference between observed evidence and private analytics", "Create an educational public-evidence teardown with permission and privacy in mind", "Explain what happens after a customer creates their own account"]],
  ["Professional outreach", ["Introduction: I use an evidence-backed growth audit to help businesses identify practical online priorities.", "Follow-up: I wanted to leave this with you in case a structured website, SEO, social, reviews, and competitor assessment would be useful.", "Scanner disclosure: This was a lightweight public static-website scan, not access to private analytics.", "Respect a no, an opt-out, or no response; do not automate repeated outreach."]],
  ["Disclosure templates", [`Social: I'm a certified partner of ${brand.name} and may earn a commission if you purchase through my link.`, "Video: This video includes my partner link. I may earn a commission if you purchase through it.", `Email: I'm an independent partner of ${brand.name} and may earn a referral commission if you subscribe using my link.`]],
  ["Consulting boundary", ["You may independently offer SEO, web, advertising, social, or consulting services.", "Set your own scope and pricing and use your own service contract.", "You are responsible for delivery, insurance, legal obligations, and taxes.", "The platform is not a party to the service agreement and does not process its payment."]],
  ["Claim matrix", ["Approved: evidence-backed findings, public competitor comparison, Action Plans, implementation drafts, grounded AI guidance, reports, and progress comparison.", "Prohibited: guaranteed growth, revenue, clients, rankings, private competitor analytics, automatic editing or publishing, fake results, and fake testimonials."]],
] as const;
export default function PartnerResourcesPage() { return <div className="grid gap-5 lg:grid-cols-2">{resources.map(([title, items]) => <Card key={title}><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent><ul className="space-y-3 text-sm leading-6 text-muted">{items.map((item) => <li key={item} className="border-l border-border pl-4">{item}</li>)}</ul></CardContent></Card>)}</div>; }
