-- CreateEnum
CREATE TYPE "BusinessGoal" AS ENUM ('MORE_CUSTOMERS', 'MORE_LEADS', 'IMPROVE_WEBSITE', 'IMPROVE_SEO', 'GROW_SOCIAL_MEDIA', 'INCREASE_SALES', 'BEAT_COMPETITORS', 'IMPROVE_BRANDING', 'INCREASE_CONVERSIONS', 'BUILD_EMAIL_LIST', 'IMPROVE_LOCAL_VISIBILITY', 'OTHER');

-- AlterTable
ALTER TABLE "Business" ADD COLUMN     "goals" "BusinessGoal"[] DEFAULT ARRAY[]::"BusinessGoal"[],
ADD COLUMN     "primaryGoal" "BusinessGoal";
