import { brand } from "@/lib/brand";
import type { PartnerPolicySection } from "@/components/partners/partner-policy-page";

// These operational drafts must receive formal legal and tax review before commercial launch.
export const partnerTermsSections: PartnerPolicySection[] = [
  { title: "Independent relationship", paragraphs: [`Certified Growth Partners are independent participants, not employees, agents, franchisees, or representatives of ${brand.name}. A partner cannot bind the company, promise exceptions, or present an exclusive territory.`, "Participation does not guarantee approval, leads, customers, conversions, income, or any business result."] },
  { title: "Customer ownership and privacy", paragraphs: ["Customers purchase directly from the platform and retain control of their accounts, Businesses, audits, reports, billing, and data. Referral attribution grants commission eligibility only.", "Partners receive no automatic customer workspace, audit, billing, or account-management access. Unauthorized access or attempted impersonation may result in immediate suspension."] },
  { title: "Independent services", paragraphs: ["A partner may separately offer consulting or implementation services using their own pricing, contract, delivery process, insurance, and tax arrangements. The platform is not a party to that agreement and does not process its payment."] },
  { title: "Compliance and termination", paragraphs: ["Partners must follow current Commission Policy, Promotion Standards, Scanner Policy, disclosure rules, privacy requirements, and applicable law. The program may suspend or terminate access for misleading claims, spam, self-referrals, fraud, privacy violations, or unsafe scanner use.", "Unpaid balances remain subject to eligibility, refunds, disputes, negative adjustments, compliance review, payout minimums, and external tax requirements after termination."] },
  { title: "Program changes", paragraphs: ["Terms and operating rules may change prospectively. Acceptance is versioned. Material updates may require reacceptance or retraining before future promotion or payouts."] },
];

export const commissionPolicySections: PartnerPolicySection[] = [
  { title: "Attribution", paragraphs: ["The first valid referral receives a 30-day attribution window by default. Attribution locks when a genuinely new account is created. Existing users and prior paying customers cannot be retroactively attributed, and self-referrals are prohibited.", "Referral attribution does not change customer pricing and creates no recruitment or downstream commission."] },
  { title: "Eligible payments", paragraphs: ["The default rate is 20% (2,000 basis points). Commission is calculated in integer cents from eligible payment subtotal after discounts and excluding tax. Zero, negative, unpaid, unsupported, refunded, or disputed amounts do not earn commission.", "A qualifying Full Audit can create one commission after verified payment. Starter and Pro can create commission for the first 12 paid subscription months by default. Checkout completion itself does not create subscription commission."] },
  { title: "Hold and availability", paragraphs: ["New commission starts pending and normally becomes available 30 days after the qualifying payment. Availability also requires active payout eligibility, current agreements, a positive net balance, and no unresolved dispute."] },
  { title: "Refunds and disputes", paragraphs: ["Full and partial refunds reduce commission proportionally. An open dispute blocks or reverses the applicable amount. A won dispute may restore only the eligible amount through a separate ledger entry.", "If a reversal occurs after payout, the completed payout remains unchanged and a negative adjustment is applied to future earnings."] },
  { title: "Manual payouts and taxes", paragraphs: ["Payouts are manual in v1. The default minimum is $50 USD. Payment method and external reference are recorded after funds are sent outside the platform. Stripe Connect is not used.", "Partners are responsible for providing required tax information through the company's external process and for their own reporting obligations. No tax identifiers or bank credentials are stored in this application."] },
];

export const promotionStandardsSections: PartnerPolicySection[] = [
  { title: "Required disclosure", paragraphs: [`Clearly disclose the financial relationship near a referral recommendation. Example: “I'm a certified partner of ${brand.name} and may earn a commission if you purchase through my link.” Vague labels such as “collab” or “supported by” are not sufficient on their own.`] },
  { title: "Approved claims", paragraphs: ["Partners may discuss evidence-backed audits, public competitor comparison, Action Plans, implementation drafts, an AI Consultant grounded in saved business information, PDF reports, Presentation Mode, and repeat-audit progress comparison."] },
  { title: "Prohibited claims", paragraphs: ["Do not promise rankings, growth, revenue, customers, conversions, passive income, or guaranteed outcomes. Do not claim private competitor analytics, post-level social performance, automatic website editing, automatic social publishing, or capabilities that are not present.", "Do not create fake testimonials, customer results, urgency, affiliations, or private-data claims."] },
  { title: "Professional outreach", paragraphs: ["Use honest subject lines and introductions. Never imply the recipient requested contact. Respect opt-outs and applicable outreach law. Mass spam, robocalling, automated texting, impersonation, and deceptive follow-up are prohibited."] },
  { title: "Brand and evidence", paragraphs: ["Use the product name and owned assets accurately. Public business teardowns must respect privacy and distinguish observed evidence from interpretation and missing data."] },
];

export const scannerPolicySections: PartnerPolicySection[] = [
  { title: "Purpose", paragraphs: ["The Partner Scanner is an optional conversation aid for active partners. It analyzes a public homepage and up to three high-priority internal pages and returns no more than three evidence-backed observations."] },
  { title: "Technical limits", paragraphs: ["The scanner uses static public HTML with bounded requests, timeouts, response-size limits, redirect validation, and private-network protections. It does not use OpenAI, Google Places, social APIs, review APIs, competitor scanning, screenshots, scores, full audits, PDFs, or implementation generation."] },
  { title: "Fair use", paragraphs: ["Default limits are 25 requests per day and 500 per month. A domain scan may be cached globally for 30 days. Bulk uploads, partner APIs, recurring background scans, and automated discovery are not permitted."] },
  { title: "Outreach use", paragraphs: ["Findings may begin a professional conversation, but they are not a complete audit. State that the scan used public static website evidence and may not see script-rendered or private information. Do not manufacture additional issues or claim hidden findings."] },
  { title: "Safety and suspension", paragraphs: ["Do not scan private networks, credentialed URLs, administrative systems, or targets you are not permitted to access. Excessive failures, evasion attempts, or unsafe use may disable scanner and referral access while administrators review the account."] },
];
